	PROGRAM INPDAT
C
C THIS PROGRAM READS N POINTS FROM A DATA FILE AND STORES THEM IN
C 3 ARRAYS X(), Y(), Z().
C
		INTEGER NMAX, U, N, I
		REAL SUMX, SUMY, SUMZ
		PARAMETER (NMAX=1000, U=20)
		REAL X(NMAX), Y(NMAX), Z(NMAX)
		DATA SUMX,SUMY,SUMZ /0,0,0/
C OPEN THE DATA FILE
		OPEN (U, FILE='randpoints.csv', STATUS='OLD',ERR=999)
C READ THE NUMBER OF POINTS
		READ(U,*) N
		IF (N.GT.NMAX) THEN
		WRITE(*,*) 'ERROR: N = ', N, 
     +		'IS LARGER THAN NMAX =', NMAX
		GOTO 9999
		ENDIF
C LOOP OVER THE DATA POINTS
		DO 10 I= 1, N
			READ(U,100) X(I), Y(I), Z(I)
			WRITE(*,100) X(I), Y(I), Z(I)
10 		CONTINUE

100 		FORMAT (3(F10.4))
C CLOSE THE FILE
		CLOSE (U)
C CALCULATE AVERAGE OF X,Y,Z DATA POINTS
		DO 20 I= 1, N
			SUMX = X(I)+SUMX
			SUMY = Y(I)+SUMY
			SUMZ = Z(I)+SUMZ
20 		CONTINUE
		WRITE(*,*) 'READ POINTS: ',N
		WRITE(*,*) 'AVG X=',SUMX/N
		WRITE(*,*) 'AVG Y=',SUMY/N
		WRITE(*,*) 'AVG Z=',SUMZ/N
		GOTO 10000		
999 	WRITE (*,*) 'ERROR IN READING THE INPUT FILE randpoints.csv'
        WRITE (*,*) 'IS THE FILE PRESENT/ACCESSIBLE?'
9999 		WRITE (*,*) 'PROGRAM TERMINATED. BYE.'
10000	END

