CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C| SUM1.F : COMPUTE THE SUM
C| OF A SUCCESSION WITH STEP S OF 
C| N INCREASING INTEGERS, TOOK
C| IN INPUT FROM THE USER
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C	CONTAINS
C ALL CALLED SUBROUTINES HERE	
	SUBROUTINE REPORT(N,S,SUM)
        INTEGER N, S, SUM
        WRITE(*,300) 'N OF ITERATIONS = ', N
        WRITE(*,300) 'STEP = ', S
        WRITE(*,200) 'FINAL SUM = ', SUM
200      FORMAT (A12,I4)
300      FORMAT (A,I2)
	END 
	
	SUBROUTINE FREPORT(N,S,SUM)
        INTEGER  N, S, SUM
        OPEN(10, FILE='RESULTS.TXT', ERR=899)
            WRITE(10,300) 'N OF ITERATIONS = ', N
            WRITE(10,300) 'STEP = ', S
            WRITE(10,200) 'FINAL SUM = ', SUM
        CLOSE(10)
        GOTO 999
200      FORMAT (A12,I4)
300      FORMAT (A,I2)
899      WRITE(*,*) 'ERROR IN WRITING FILE'
999	END

	
C ACCESS='SEQUENTIAL',

	PROGRAM SUM1
		IMPLICIT NONE
		INTEGER I, N, S, MYSUM, DEBUG
		MYSUM = 0
		DEBUG = 0
C READ NUMBER OF ITERATION FROM STDIN
10		WRITE(*,*) 'PLEASE ENTER N. OF ITERATIONS (1-99)'
		READ(*,*) N
		IF ((N.GE.100) .OR. (N.LT.1)) THEN
            WRITE(*,*) 'ONLY INTEGERS IN THE INTERVAL (1-99)'
            WRITE(*,*) 'ARE ALLOWED'
            GOTO 10
		END IF
20		WRITE(*,*) 'PLEASE ENTER STEP VALUE (1-99)'
		READ(*,*) S
C READ STEP VALUE FROM STDIN		
		IF ( (S.GE.100) .OR. (S.LT.1) ) THEN
            WRITE(*,*) 'ONLY INTEGERS IN THE INTERVAL (1-99)'
            WRITE(*,*) 'ARE ALLOWED'
            GOTO 20
		END IF
		IF (S.GE.N)  THEN
            WRITE(*,*) 'THE STEP MUST BE GREATER OF '
            WRITE(*,*) 'NUMBER OF ITERATIONS'
            GOTO 20
		END IF

		DO 50 I = 1, N, S
			MYSUM = MYSUM + I
			IF (DEBUG.GT.0) THEN 
                WRITE(*,100) 'I =', I, ' SUM =', MYSUM	
			END IF		
50 		CONTINUE
          CALL REPORT(N,S,MYSUM)          
C DEFINE LINE OF OUTPUT FORMAT
100		 FORMAT (A3,I2,A6,I4)
	END

