CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C| SUM1.F : COMPUTE THE SUM
C| OF A SUCCESSION WITH STEP S OF 
C| N INCREASING INTEGERS, TOOK
C| IN INPUT FROM THE USER
CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
C ALL CALLED SUBROUTINES HERE	
	SUBROUTINE REPORT
        INTEGER N, S, SUM
        WRITE(*,*) 'N OF ITERATIONS = ', N
        WRITE(*,*) 'STEP = ', S
        WRITE(*,*) 'FINAL SUM = ', SUM
	END 
	
	SUBROUTINE FREPORT(N,S,SUM)
        INTEGER  N, S, SUM
        OPEN(10, FILE='results.txt', ACCESS='SEQUENTIAL'
     1   ,ERR=899)
            WRITE(10,100) 'N OF ITERATIONS = ', N
            WRITE(10,100) 'STEP = ', S
            WRITE(10,100) 'FINAL SUM = ', SUM
        CLOSE(10)
            WRITE(*,*) 'RESULTS OUTPUT TO FILE results.txt'
            GOTO 999
100	FORMAT(A16,I10)
899      WRITE(*,*) 'ERROR IN WRITING FILE'
999	END

C HERE STARTS THE MAIN PROGRAM
	PROGRAM SUM1
		INTEGER I, N, S, SUM, DEBUG
		SUM = 0
		DEBUG = 0
C READ NUMBER OF ITERATION FROM STDIN
10		WRITE(*,*) 'PLEASE ENTER N. OF ITERATIONS (1-99)'
		READ(*,*) N
		IF ((N.GE.100) .OR. (N.LT.1)) THEN
            WRITE(*,*) 'ONLY INTEGERS IN THE INTERVAL (1-99)'
            WRITE(*,*) 'ARE ALLOWED'
            GOTO 10
		END IF
20		WRITE(*,*) 'PLEASE ENTER STEP VALUE (1-99)'
		READ(*,*) S
C READ STEP VALUE FROM STDIN		
		IF ( (S.GE.100) .OR. (S.LT.1) ) THEN
            WRITE(*,*) 'ONLY INTEGERS IN THE INTERVAL (1-99)'
            WRITE(*,*) 'ARE ALLOWED'
            GOTO 20
		END IF
		IF (S.GE.N)  THEN
            WRITE(*,*) 'THE STEP MUST BE SMALLER OF '
            WRITE(*,*) 'NUMBER OF ITERATIONS'
            GOTO 20
		END IF

		DO 50 I = 1, N, S
			SUM = SUM + I
			IF (DEBUG.GT.0) THEN 
                WRITE(*,100) 'I =', I, ' SUM =', SUM	
			END IF		
50 		CONTINUE
          CALL FREPORT(N,S,SUM)           
C DEFINE LINE OF OUTPUT FORMAT
100		 FORMAT (A3,I2,A6,I4)
200      FORMAT (A12,I4)
300      FORMAT (A,I2)


	END
